[package]
name = "tergrrs"
version = "0.2.2"
authors = ["thash <hash@hzl.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
