name: Bump Cargo files and create new release PR
on:
  workflow_dispatch:
    # https://docs.github.com/en/webhooks/event-payloads/#workflow_dispatch
    inputs:
      new_release_version:
        description: New version to release (e.g. "1.0.12")
        required: true

env:
  PROJECT_NAME: tergrrs

jobs:
  update_cargo_files_and_create_pull_request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Retrieve CLI_VERSION from Cargo.toml
      shell: bash
      run: |
        CURRENT_CLI_VERSION=$(grep "version =" Cargo.toml | sed -e 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/g')
        echo "CURRENT_CLI_VERSION retrieved from Cargo.toml is: ${CURRENT_CLI_VERSION}"
        # set for subsequent steps
        echo "CURRENT_CLI_VERSION=${CURRENT_CLI_VERSION}" >> $GITHUB_ENV
    - name: Confirm version change
      shell: bash
      run: |
        echo "Cargo.toml contains current version: ${{ env.CURRENT_CLI_VERSION }}."
        echo "... will be updated to the manually entered new version: ${{ github.event.inputs.new_release_version }}."
        # if [[ ${{ github.event.inputs.new_release_version }} == ${{ env.CURRENT_CLI_VERSION }} ]]; then exit 1; fi
    - name: Check versions defined in Cargo.*
      run: |
        echo "Cargo.toml: "; grep -e "^version = " Cargo.toml
        echo "Cargo.lock: "; grep -A 2 ${{ env.PROJECT_NAME }} Cargo.lock
    - name: Replace Cargo.toml version to ${{ github.event.inputs.new_release_version }}
      run: |
        sed -i -e 's/^version = "[0-9]\+\.[0-9]\+\.[0-9]\+"/version = "${{ github.event.inputs.new_release_version }}"/' Cargo.toml
    - name: Execute cargo build to update Cargo.lock
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - name: Check versions defined in Cargo.*
      run: |
        echo "Cargo.toml: "; grep -e "^version = " Cargo.toml
        echo "Cargo.lock: "; grep -A 2 ${{ env.PROJECT_NAME }} Cargo.lock
    # - name: Create changelog from PRs between current to new version
    #   uses: actions/github-script@v3
    #   with:
    #     github-token: ${{ github.token }}
    #     script: |
    #       github.git.createRef({
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         ref: "refs/tags/v${{ needs.build_binaries.outputs.cli_version }}",
    #         sha: context.sha
    #       })
    - name: Create Pull Request
      id: create_pull_request
      uses: peter-evans/create-pull-request@v3
      with:
        title: [workflow] Bump version v${{ env.CURRENT_CLI_VERSION }} -> v${{ github.event.inputs.new_release_version }} 
        branch: bump-v${{ github.event.inputs.new_release_version }}
        commit-message: [workflow] Bump version to v${{ github.event.inputs.new_release_version }}
        draft: true
        delete-branch: true
        body: |
          TODO: Using previously merged pull requests, generate "changelog" text that can be used to this PR body. Then, reuse it for the release note as well.
          aaa
          // To make a specific step reusalbe: https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action
          NOTE: This Pull Request is automatically generated by a workflow (see: .github/workflows).
    - name: Check outputs of the created Pull Request
      run: |
        echo "Pull Request Number - ${{ steps.create_pull_request.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.create_pull_request.outputs.pull-request-url }}"