name: Bump Cargo files and create new release PR
on:
  workflow_dispatch:
    # https://docs.github.com/en/webhooks/event-payloads/#workflow_dispatch
    inputs:
      new_release_version:
        description: New version number to release (e.g. 0.1.23)
        required: true

env:
  PROJECT_NAME: tergrrs

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Retrieve CLI_VERSION from Cargo.toml
      shell: bash
      run: |
        CURRENT_CLI_VERSION=$(grep "version =" Cargo.toml | sed -e 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/g')
        echo "CURRENT_CLI_VERSION retrieved from Cargo.toml is: ${CURRENT_CLI_VERSION}"
        # set for subsequent steps
        echo "CURRENT_CLI_VERSION=${CURRENT_CLI_VERSION}" >> $GITHUB_ENV
    - name: Confirm version change
      shell: bash
      run: |
        echo "Cargo.toml contains current version: ${{ env.CURRENT_CLI_VERSION }}."
        echo "... will be updated to the manually entered new version: ${{ github.event.inputs.new_release_version }}."
        # if [[ ${{ github.event.inputs.new_release_version }} == ${{ env.CURRENT_CLI_VERSION }} ]]; then exit 1; fi
    - name: Check versions defined in Cargo.*
      run: |
        grep -e "^version = " Cargo.toml
        grep -A 2 ${{ env.PROJECT_NAME }} Cargo.lock
    - name: Replace Cargo.toml version to ${{ github.event.inputs.new_release_version }}
      run: |
        sed -i -e 's/^version = "[0-9]\+\.[0-9]\+\.[0-9]\+"/version = "${{ github.event.inputs.new_release_version }}"/' Cargo.toml
    - name: Execute cargo build to update Cargo.lock
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - name: Check versions defined in Cargo.*
      run: |
        grep -e "^version = " Cargo.toml
        grep -A 2 ${{ env.PROJECT_NAME }} Cargo.lock